### ISSUE TITLE
Incorrect coloring

### ISSUE THREAD

**Issue by tiansin** [dannymcgee/vscode-go-syntax#1]
@dannymcgee  Thank you very much for this extension, but I found several coloring issues during use.

![Screen Shot 2021-01-22 at 15 14 29](https://user-images.githubusercontent.com/4232281/105459300-fb09c900-5cc4-11eb-9eb9-1c13add87a90.png)
![Screen Shot 2021-01-22 at 15 15 09](https://user-images.githubusercontent.com/4232281/105459303-fcd38c80-5cc4-11eb-8609-ca5610263fba.png)
![Screen Shot 2021-01-22 at 15 15 30](https://user-images.githubusercontent.com/4232281/105459305-fd6c2300-5cc4-11eb-8f33-2cebefcc9e6a.png)

**Comment by dannymcgee** [comment]
@tiansin Thanks for the heads up! I'll get this taken care of tomorrow.

Would you be able to post a bigger chunk of the problematic code? I see what's happening in the 3rd screenshot, but I'm not 100% sure what's happening in the 1st and 2nd. Also, could you let me know what theme you're using?

**Comment by tiansin** [comment]
@dannymcgee Thanks for answering, this is the theme I use.The range and select keyword in the 1st and 2nd images is incorrectly colored.
https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme

**Comment by dannymcgee** [comment]
@tiansin Thanks for the info! This should be all fixed in 1.0.3 (may need to give it a few minutes for the updates to come through). Let me know if you encounter any other issues.

**Comment by tiansin** [comment]
@dannymcgee Thank you for your repair. In addition, I also installed the enhancement tools you provided
https://github.com/dannymcgee/golang-tools/tree/semantic-tokens
It doesn't seem to have any special effect.


![Screen Shot 2021-01-25 at 14 37 47](https://user-images.githubusercontent.com/4232281/105669906-1f5ee300-5f1b-11eb-8b6f-f07e816edcd4.png)
Can you tell me what font is this? It looks very good.

**Comment by dannymcgee** [comment]
@tiansin The font is [Operator Mono](https://www.typography.com/fonts/operator/overview), with coding ligatures added from [this project](https://github.com/kiliman/operator-mono-lig)

For the custom gopls branch, I should probably add some better instructions to the readme. You need to do the following:

1. Download the repo to your GOPATH at `src/golang.org/x/tools`
2. `cd` into `tools/gopls` and run `go install`
3. Configure the official VS Code Go extension to use the gopls language server and enable semantic tokens:
   ```
   "go.useLanguageServer": true,
   "gopls": {
       "ui.semanticTokens": true
   }
   ```

**Comment by tiansin** [comment]
@dannymcgee Thank you very much, it does work for it.
