### ISSUE TITLE
Escaped backslash not handled correctly when preceding a rune or string delimiter

### ISSUE THREAD

**Issue by 0x000777** [dannymcgee/vscode-go-syntax#3]
Bug hightlight. Use char (rune)

![image](https://user-images.githubusercontent.com/17083227/111330883-65196b80-8681-11eb-8c09-9aaf9d072c58.png)

**Comment by dannymcgee** [comment]
Thanks for the heads up @Highter87 — it looks like there's an issue with the way I'm handling escaped delimiters. I'll take a look at this later today and see if I can come up with a solution.

**Comment by 0x000777** [comment]
https://github.com/dannymcgee/vscode-go-grammar/blob/main/src/repository/literals.ts#L99

**Comment by 0x000777** [comment]
try this `(?<![\\])'|(?<=[\\]{2})'`

**Comment by dannymcgee** [comment]
That did the trick, thanks @Highter87 ! Fixed in 1.0.4
